---
# tasks file for sublime
- name: install key (apt)
  apt_key:
    url: 'https://download.sublimetext.com/sublimehq-pub.gpg'
    state: present
- name: install sublime repo (apt)
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    filename: sublime-text
    state: present
- name: install sublime-text (apt)
  apt:
    name: sublime-text
    state: present