---
- name: add skype repo key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY

- name: add skype repo
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype-stable

- name: install skype
  apt:
    name: skypeforlinux