  - name: standard Playbook
    hosts : addweb
    # default strategy is liner means run with parallell machine ,In Free it will we run serial vise 
    # strategy: linear or free
    # set serial limitation
    # serial: 1    
    # become_user: root
    vars:
      ansible_python_interpreter: /usr/bin/python3
    become: true
    roles:
     - common
     - skype
     - chrome
     - sublime
     - rocketchat
     - anydesk
     - slack
     - docker
     - dockerenv
     - VCS
     - vagrant    
#     - reboot
   
